jobs:
- job: Windows_VS2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir build
      cd build
      cmake .. -G "Visual Studio 16 2019" -A x64
      MSBuild.exe ..\build\biovault_bfloat16.sln /property:Configuration=Release
      cd ..
    displayName: $(Agent.JobName) Visual C++ build
  - script: |
      .\build\Release\biovault_bfloat16_test.exe
    displayName: $(Agent.JobName) run

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      mkdir build
      cd build
      cmake ..
      make
      cd ..
    displayName: $(Agent.JobName) GCC build
  - script: |
      ./build/biovault_bfloat16_test
    displayName: $(Agent.JobName) run
   
- job: MacOS
  pool:
    vmImage: 'macOS-13'
  steps:
  - script: |
      mkdir build
      cd build
      cmake ..
      make
      cd ..
    displayName: $(Agent.JobName) Clang build
  - script: |
      ./build/biovault_bfloat16_test
    displayName: $(Agent.JobName) run

